version: '3'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db_network

  app:
    container_name: api_server
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - db_network


networks:
  db_network:
    driver: bridge